import React from 'react'


export const metadata = {
    title: "Monthly Data || MoneyMap",
    description: "Generated by create next app",
  };

export default function LayoutMonthlyData({children}) {
  return (
    <div>
      {children}
    </div>
  )
}