import React from 'react'


export const metadata = {
    title: "Expense || MoneyMap",
    description: "Generated by create next app",
  };

export default function LayoutExpense({children}) {
  return (
    <div>
      {children}
    </div>
  )
}
