import { Inter } from "next/font/google";
import "./globals.css";
import { FaPlus } from "react-icons/fa6";
import { MdOutlineAccountCircle } from "react-icons/md";
import logo from "../public/log.png";
import Image from "next/image";
import Button from "./components/Button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MoneyMap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className="flex justify-between items-center px-3 py-3 fixed bottom-0 w-[400px] z-100000000 bg-zinc-300 ">
            <Button>
            <p className="w-[30px] h-[30px] rounded-full bg-gray-900 text-lime-300 flex justify-center items-center">
              <FaPlus />
            </p>
            </Button>
            <Image alt="" src={logo} className="w-[90px]" />

            <Link href='/profile'>
            <p className="w-[30px] h-[30px] rounded-full bg-gray-900 text-lime-300 flex justify-center items-center">
              <MdOutlineAccountCircle />
            </p>
            </Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
