import { Inter } from "next/font/google";
import "./globals.css";
import { FaPlus } from "react-icons/fa6";
import { MdOutlineAccountCircle } from "react-icons/md";
import logo from "../public/log.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-[400px]">
      <body className={inter.className}>
        <nav className="flex justify-between items-center px-3 py-3 fixed bottom-0 w-[400px] border-2 z-100000000 bg-zinc-300">
          <p className="w-[30px] h-[30px] rounded-full bg-gray-900 text-lime-300 flex justify-center items-center">
            <FaPlus />
          </p>
          <Image alt="" src={logo} className="w-[90px]" />
          <p className="w-[30px] h-[30px] rounded-full bg-gray-900 text-lime-300 flex justify-center items-center">
            <MdOutlineAccountCircle />
          </p>
        </nav>
        {children}
      </body>
    </html>
  );
}
