import React from 'react'


export const metadata = {
    title: "MoneyMap || Profile",
    description: "Generated by create next app",
  };

export default function LayoutCurrentMonth({children}) {
  return (
    <div>
      {children}
    </div>
  )
}